<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>DataAccess</AssemblyName>
    <RootNamespace>MockTrader.Data</RootNamespace>
  </PropertyGroup>
</Project>
